
spring.cloud.aws:
  credentials:
    access-key: AKIARF2ZW7GNC5QG6AN4
    secret-key: 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
    #access-key: AKIARF2ZW7GNP36NHV5S
    #secret-key: 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
  region.static: us-east-2

